name: toolkit-unit-tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm run format:check
        if: matrix.runs-on == 'ubuntu-latest'
      - run: npm run lint
        if: matrix.runs-on == 'ubuntu-latest'
      - run: npm run test
      - run: npm run build:check
